name: Publish PowerShell Module

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  publish-module:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install and cache PowerShell modules
        id: psmodulecache
        uses: potatoqualitee/psmodulecache@v5.2
        with:
          modules-to-cache: PowerShellGet, PackageManagement
          shell: pwsh
      # Push the updated module to the PowerShell Gallery
      - id: check_if_versions_bumped
        shell: pwsh
        run: |
          [version]$GalleryVersion =  (Find-Module -Name count-loc -Repository PSGallery).Version
          [Version]$GithubVersion = (Import-PowerShellDataFile -Path $(Join-Path -Path "count-loc" -ChildPath "count-loc.psd1")).ModuleVersion
          $bumped = $GithubVersion -ge $GalleryVersion
          Write-Host "::set-output name=version_bumped::$bumped"
      # Set the output named "version_bumped"
      - name: Push module to PowerShell Gallery
        if: steps.check_if_versions_bumped.outputs.version_bumped == 'True'
        shell: pwsh
        run: |
          $params = @{
              Path        = "${{ github.workspace }}/count-loc"
              NuGetApiKey = "${{ secrets.NUGET_KEY }}"
              ErrorAction = "Stop"
          }
          Publish-Module @params
